bootstrap.servers=kafka:9092
group.id=energy-cdc-connect
config.storage.topic=energy-cdc-connect-configs
offset.storage.topic=energy-cdc-connect-offsets
status.storage.topic=energy-cdc-connect-statuses
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
key.converter.schemas.enable=false
value.converter.schemas.enable=false
config.providers=file
config.providers.file.class=org.apache.kafka.common.config.provider.FileConfigProvider
plugin.path=/opt/connect-plugins
listeners=http://0.0.0.0:8083
rest.advertised.host.name=debezium-connect
rest.advertised.port=8083
